SWIPL Zwapel: prolog.cc File Reference
prolog.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <ctype.h>
#include <wchar.h>
#include <limits.h>
#include <unistd.h>
#include <getopt.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <iostream>
#include <string>
#include <sstream>
#include <fstream>
#include <istream>
#include <codecvt>
#include <exception>
#include <vector>
#include <algorithm>
#include <iterator>
#include <csignal>
Classes
struct PL_Exception
Macros
#define STDCOUT std::cout
Functions
int main (int argc, char **argv)
void on_setMode (std::string mode)
int PL_fail ()
int PL_success ()
std::string readFile (const std::string filename)
Variables
int convert_mode = 0
const int CVT_ASM = 1
const int CVT_NONE = 0
const int CVT_PASCAL = 2
std::ifstream iput_file
std::string iput_file_str
std::ofstream oput_file
std::string oput_file_str
std::string PL_ident
uint64_t PL_lineno
uint64_t PL_lookaheadPosition
uint8_t PL_lookaheadWChar
uint64_t PL_nestedComment
Macro Definition Documentation
STDCOUT
#define STDCOUT std::cout
Definition at line 110 of file prolog.cc.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 159 of file prolog.cc.
References iput_file, iput_file_str, PL_Exception::message, oput_file, PL_fail(), PL_ident, PL_lineno, PL_lookaheadPosition, PL_lookaheadWChar, PL_nestedComment, PL_success(), readFile(), and STDCOUT.
on_setMode()
void on_setMode (std::string mode)
Definition at line 130 of file prolog.cc.
References convert_mode, CVT_ASM, and CVT_PASCAL.
PL_fail()
int PL_fail () inline
Definition at line 103 of file prolog.cc.
Referenced by main(), and pl_show_message().
PL_success()
int PL_success () inline
Definition at line 102 of file prolog.cc.
Referenced by main().
readFile()
std::string readFile (const std::string filename)
Definition at line 140 of file prolog.cc.
References iput_file.
Referenced by main().
Variable Documentation
convert_mode
int convert_mode = 0
Definition at line 78 of file prolog.cc.
Referenced by on_setMode().
CVT_ASM
const int CVT_ASM = 1
Definition at line 75 of file prolog.cc.
Referenced by on_setMode().
CVT_NONE
const int CVT_NONE = 0
Definition at line 74 of file prolog.cc.
CVT_PASCAL
const int CVT_PASCAL = 2
Definition at line 76 of file prolog.cc.
Referenced by on_setMode().
iput_file
std::ifstream iput_file
Definition at line 96 of file prolog.cc.
Referenced by main(), and readFile().
iput_file_str
std::string iput_file_str
Definition at line 93 of file prolog.cc.
Referenced by main().
oput_file
std::ofstream oput_file
Definition at line 97 of file prolog.cc.
Referenced by main().
oput_file_str
std::string oput_file_str
Definition at line 94 of file prolog.cc.
PL_ident
std::string PL_ident
Definition at line 112 of file prolog.cc.
Referenced by main().
PL_lineno
uint64_t PL_lineno
Definition at line 116 of file prolog.cc.
Referenced by main().
PL_lookaheadPosition
uint64_t PL_lookaheadPosition
Definition at line 115 of file prolog.cc.
Referenced by main().
PL_lookaheadWChar
uint8_t PL_lookaheadWChar
Definition at line 111 of file prolog.cc.
Referenced by main().
PL_nestedComment
uint64_t PL_nestedComment
Definition at line 117 of file prolog.cc.
Referenced by main().