/* This file was generated by PortableXDR rpcgen 4.9.2
 * ANY CHANGES YOU MAKE TO THIS FILE MAY BE LOST!
 * The input file was service.x
 */

#ifndef RPCGEN_HEADER_SERVICE_H
#define RPCGEN_HEADER_SERVICE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <rpc/rpc.h>

/* Use the following symbol in your code to detect whether
 * PortableXDR's rpcgen was used to compile the source file.
 */
#define PORTABLE_RPCGEN_SERVICE 1

#line 11 "service.x"
struct netuser {
  int8_t *name;
  int32_t id;
};
typedef struct netuser netuser;
extern bool_t xdr_netuser (XDR *, netuser *);

int
xdr_netuser(XDR *xdrs, struct netuser *nu)
{
 return (xdr_string(xdrs, &nu->name, 255));
}
#line 21 "service.x"

#ifdef __cplusplus
}
#endif

#endif /* RPCGEN_HEADER_SERVICE_H */

/* EOF */
