/* This file was generated by PortableXDR rpcgen 4.9.2
 * ANY CHANGES YOU MAKE TO THIS FILE MAY BE LOST!
 * The input file was service.x
 */

#include "service.h"

#line 11 "service.x"
bool_t
xdr_netuser (XDR *xdrs, netuser *objp)
{
  if (!xdr_pointer (xdrs, (char **)objp, 1, (xdrproc_t) xdr_char))
    return FALSE;
  if (!xdr_int (xdrs, &objp->id))
    return FALSE;
  return TRUE;
}

int
xdr_netuser(XDR *xdrs, struct netuser *nu)
{
 return (xdr_string(xdrs, &nu->name, 255));
}
#line 21 "service.x"

/* EOF */
