SWIPL Zwapel: main.cc File Reference
main.cc File Reference
#include <iostream>
#include "prolog.h"
Classes
struct zwap_funcs
Macros
#define gui_func(name) dlsym(get_zwap_handle(),name)
Typedefs
typedef void(__stdcall * ref_show_message) (LPCSTR, LPCSTR)
typedef struct zwap_funcs zwap_funcs
Functions
void __attribute__ ((constructor)) my_init(void)
void __attribute__ ((destructor)) my_fini(void)
void * get_zwap_handle ()
const char * get_zwap_name ()
static void init_stuff (void)
install_t install_zwapwin64 ()
static foreign_t pl_show_message (term_t a0, int arity, void *context)
Variables
zwap_funcs zwap_func
void * zwap_mod_handle
Macro Definition Documentation
gui_func
#define gui_func (name) dlsym(get_zwap_handle(),name)
Typedef Documentation
ref_show_message
typedef void(__stdcall * ref_show_message) (LPCSTR, LPCSTR)
Definition at line 26 of file main.cc.
zwap_funcs
typedef struct zwap_funcs zwap_funcs
Function Documentation
__attribute__() [1/2]
void __attribute__ ((constructor))
Definition at line 168 of file main.cc.
References zwap_mod_handle.
__attribute__() [2/2]
void __attribute__ ((destructor))
Definition at line 179 of file main.cc.
References get_zwap_handle().
get_zwap_handle()
void * get_zwap_handle () inline
Definition at line 23 of file main.cc.
References zwap_mod_handle.
Referenced by __attribute__(), and init_stuff().
get_zwap_name()
const char * get_zwap_name () inline
Definition at line 22 of file main.cc.
init_stuff()
static void init_stuff (void) static
Definition at line 48 of file main.cc.
References get_zwap_handle(), zwap_funcs::show_message, and zwap_func.
install_zwapwin64()
install_t install_zwapwin64 ()
Definition at line 93 of file main.cc.
References pl_show_message().
pl_show_message()
static foreign_t pl_show_message (term_t a0, int arity, void * context) static
Definition at line 71 of file main.cc.
References PL_fail(), zwap_funcs::show_message, and zwap_func.
Referenced by install_zwapwin64().
Variable Documentation
zwap_func
zwap_funcs zwap_func
Definition at line 32 of file main.cc.
Referenced by init_stuff(), and pl_show_message().
zwap_mod_handle
void* zwap_mod_handle
Definition at line 20 of file main.cc.
Referenced by __attribute__(), and get_zwap_handle().