
#line 2 "lex.pascal.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer pascal_create_buffer
#define yy_delete_buffer pascal_delete_buffer
#define yy_scan_buffer pascal_scan_buffer
#define yy_scan_string pascal_scan_string
#define yy_scan_bytes pascal_scan_bytes
#define yy_init_buffer pascal_init_buffer
#define yy_flush_buffer pascal_flush_buffer
#define yy_load_buffer_state pascal_load_buffer_state
#define yy_switch_to_buffer pascal_switch_to_buffer
#define yypush_buffer_state pascalpush_buffer_state
#define yypop_buffer_state pascalpop_buffer_state
#define yyensure_buffer_stack pascalensure_buffer_stack
#define yy_flex_debug pascal_flex_debug
#define yyin pascalin
#define yyleng pascalleng
#define yylex pascallex
#define yylineno pascallineno
#define yyout pascalout
#define yyrestart pascalrestart
#define yytext pascaltext
#define yywrap pascalwrap
#define yyalloc pascalalloc
#define yyrealloc pascalrealloc
#define yyfree pascalfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define pascal_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer pascal_create_buffer
#endif

#ifdef yy_delete_buffer
#define pascal_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer pascal_delete_buffer
#endif

#ifdef yy_scan_buffer
#define pascal_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer pascal_scan_buffer
#endif

#ifdef yy_scan_string
#define pascal_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string pascal_scan_string
#endif

#ifdef yy_scan_bytes
#define pascal_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes pascal_scan_bytes
#endif

#ifdef yy_init_buffer
#define pascal_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer pascal_init_buffer
#endif

#ifdef yy_flush_buffer
#define pascal_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer pascal_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define pascal_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state pascal_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define pascal_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer pascal_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define pascalpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state pascalpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define pascalpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state pascalpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define pascalensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack pascalensure_buffer_stack
#endif

#ifdef yylex
#define pascallex_ALREADY_DEFINED
#else
#define yylex pascallex
#endif

#ifdef yyrestart
#define pascalrestart_ALREADY_DEFINED
#else
#define yyrestart pascalrestart
#endif

#ifdef yylex_init
#define pascallex_init_ALREADY_DEFINED
#else
#define yylex_init pascallex_init
#endif

#ifdef yylex_init_extra
#define pascallex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra pascallex_init_extra
#endif

#ifdef yylex_destroy
#define pascallex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy pascallex_destroy
#endif

#ifdef yyget_debug
#define pascalget_debug_ALREADY_DEFINED
#else
#define yyget_debug pascalget_debug
#endif

#ifdef yyset_debug
#define pascalset_debug_ALREADY_DEFINED
#else
#define yyset_debug pascalset_debug
#endif

#ifdef yyget_extra
#define pascalget_extra_ALREADY_DEFINED
#else
#define yyget_extra pascalget_extra
#endif

#ifdef yyset_extra
#define pascalset_extra_ALREADY_DEFINED
#else
#define yyset_extra pascalset_extra
#endif

#ifdef yyget_in
#define pascalget_in_ALREADY_DEFINED
#else
#define yyget_in pascalget_in
#endif

#ifdef yyset_in
#define pascalset_in_ALREADY_DEFINED
#else
#define yyset_in pascalset_in
#endif

#ifdef yyget_out
#define pascalget_out_ALREADY_DEFINED
#else
#define yyget_out pascalget_out
#endif

#ifdef yyset_out
#define pascalset_out_ALREADY_DEFINED
#else
#define yyset_out pascalset_out
#endif

#ifdef yyget_leng
#define pascalget_leng_ALREADY_DEFINED
#else
#define yyget_leng pascalget_leng
#endif

#ifdef yyget_text
#define pascalget_text_ALREADY_DEFINED
#else
#define yyget_text pascalget_text
#endif

#ifdef yyget_lineno
#define pascalget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno pascalget_lineno
#endif

#ifdef yyset_lineno
#define pascalset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno pascalset_lineno
#endif

#ifdef yywrap
#define pascalwrap_ALREADY_DEFINED
#else
#define yywrap pascalwrap
#endif

#ifdef yyalloc
#define pascalalloc_ALREADY_DEFINED
#else
#define yyalloc pascalalloc
#endif

#ifdef yyrealloc
#define pascalrealloc_ALREADY_DEFINED
#else
#define yyrealloc pascalrealloc
#endif

#ifdef yyfree
#define pascalfree_ALREADY_DEFINED
#else
#define yyfree pascalfree
#endif

#ifdef yytext
#define pascaltext_ALREADY_DEFINED
#else
#define yytext pascaltext
#endif

#ifdef yyleng
#define pascalleng_ALREADY_DEFINED
#else
#define yyleng pascalleng
#endif

#ifdef yyin
#define pascalin_ALREADY_DEFINED
#else
#define yyin pascalin
#endif

#ifdef yyout
#define pascalout_ALREADY_DEFINED
#else
#define yyout pascalout
#endif

#ifdef yy_flex_debug
#define pascal_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug pascal_flex_debug
#endif

#ifdef yylineno
#define pascallineno_ALREADY_DEFINED
#else
#define yylineno pascallineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[585] =
    {   0,
       16,   16,    8,    8,    0,    0,    0,    0,   83,   81,
       16,   17,   17,   81,   73,   74,   79,   77,   71,   78,
       70,   80,   66,   69,   68,   72,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   75,   76,   13,   17,
       82,    8,   82,   11,   82,   14,   15,   16,    3,   10,
        5,    7,    1,    0,   66,   65,   65,   65,    0,   65,
        0,   65,   65,   65,    0,   65,   26,   26,   65,   65,
        0,   65,   65,   65,    0,   65,    0,   35,   65,   37,
       35,   65,   65,    0,   65,    0,   65,   65,    0,   44,

       45,   44,   65,   65,   65,    0,   65,    0,   65,    0,
       65,   57,   65,   57,   65,   65,    0,   65,    0,   65,
       65,    0,    0,    0,   35,    0,    0,    0,    0,   37,
       26,   45,    0,    0,    0,   26,    8,    0,    9,   12,
        3,    4,    5,    6,    1,    2,    0,   67,   19,   19,
       65,    0,   19,   65,    0,   65,    0,   65,    0,   65,
        0,    0,   25,   25,   65,    0,   25,   65,    0,   29,
       29,   29,   65,    0,   31,   31,   65,    0,   31,   65,
        0,   65,    0,   65,    0,    0,   65,    0,   65,    0,
        0,   41,   41,   42,   42,   43,   43,   42,   65,    0,

       65,   65,    0,   65,    0,    0,    0,    0,   65,   65,
        0,    0,    0,   55,   55,   65,    0,   65,    0,    0,
       65,   65,    0,   65,    0,    0,    0,    0,   62,   62,
       65,    0,   65,    0,    0,   62,   55,    0,   42,   25,
        0,   19,    0,   19,   43,   31,    0,    0,    0,    0,
       19,    0,    0,    0,    0,   31,    0,   43,   19,    0,
       18,   65,    0,   65,    0,   22,   22,   65,    0,   65,
        0,    0,   22,   65,    0,   28,   28,   30,   30,   65,
        0,   65,    0,   30,   34,   34,   65,    0,   65,    0,
        0,   65,    0,   65,    0,    0,   65,    0,   65,    0,

       65,   65,   65,    0,    0,    0,    0,    0,   65,    0,
        0,   65,    0,   65,    0,    0,   56,   56,   58,   58,
       56,   59,   59,   65,    0,   59,   61,   61,   59,   65,
        0,   64,   64,   64,   22,   22,    0,   56,   30,   28,
        0,   59,   34,    0,    0,    0,    0,   56,   59,    0,
       58,   58,    0,   22,   34,    0,   22,    0,    0,   56,
       34,   61,   59,   22,   20,   20,   21,   21,   23,   23,
       24,   24,   23,   65,    0,   65,    0,   65,    0,    0,
       65,    0,   65,    0,    0,   39,   39,   65,    0,   39,
       65,    0,   65,    0,   65,    0,   65,    0,   65,    0,

        0,    0,    0,   65,    0,    0,    0,   65,    0,   65,
        0,    0,   60,   60,   63,   63,   39,   21,   60,   24,
       24,   20,    0,   39,    0,   63,   24,    0,   20,    0,
       39,   21,   63,   63,    0,   63,   39,    0,   24,   20,
       27,   27,   65,    0,   65,    0,    0,   65,    0,   65,
        0,    0,   65,    0,   46,   46,   65,    0,   65,    0,
       65,    0,   65,    0,    0,    0,    0,   51,   65,   51,
       51,    0,   46,   46,   51,   46,   53,   53,   54,   54,
       53,   27,   51,   51,   46,   54,    0,   54,   51,    0,
       54,   54,   46,   53,   27,   46,   27,   32,   32,   65,

        0,   32,   65,    0,   65,    0,    0,   40,   40,   47,
       47,   65,    0,   49,   49,   65,    0,    0,   49,   47,
       65,    0,   47,    0,   40,    0,    0,   32,   32,    0,
       49,   47,   32,   33,   33,   65,    0,   65,    0,    0,
       65,    0,   65,    0,    0,   65,    0,    0,    0,   33,
       33,    0,    0,   33,   33,   65,    0,   38,   38,   38,
       48,   48,   50,   50,   48,   52,   52,   50,   48,   52,
       48,   38,   38,   65,    0,   65,    0,   65,    0,   65,
        0,   36,   36,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    5,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,    1,
       17,    1,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       27,   34,   35,   36,   37,   38,   39,   27,   40,   27,
       41,    1,   42,    1,    1,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   27,   34,   35,   36,   37,   38,   39,   27,
       40,   27,   43,   44,   45,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[46] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    1,    1,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        1,    1,    1,    2,    1
    } ;

static const flex_int16_t yy_base[590] =
    {   0,
        0,    0,   43,   44,   45,   46,   47,   52, 1279, 1280,
     1276, 1280, 1280, 1272, 1268, 1280, 1267, 1280, 1280, 1280,
     1280,   48,   45, 1280, 1280, 1280,   29,   36,   46,   39,
       37,   50,   30, 1230,   54,   70,   35,   63,   68,   81,
       64,   78,   79,   82,   83,   80, 1280, 1280, 1280,  110,
     1280, 1270,  108, 1280, 1265, 1280, 1280, 1269, 1267, 1280,
     1266, 1280, 1265,   58,  117, 1223,   99,   59,  117,   86,
      113,  111,  116,  118,  134,  115,  119,  128,  129,  127,
      135,  139,  140,  144,  151,  145,  150, 1222,  143,  154,
      160,  158,  172,  173,  176,  178,  171,  165,  174, 1221,

     1220, 1280,  185,  180,  188,  207,  201,  203,  175,  194,
      191, 1219,  181,  209,  214,  215,  226,  210,  212,  217,
      205,  229,  244,  247, 1280,  246,  256,  242,  243,  263,
      272,  270,  273,  238,  265,  300, 1259,  297, 1280, 1280,
     1258, 1280, 1257, 1280, 1256, 1280,  301, 1244, 1213, 1280,
      279,  283,  307,  286,  302,  315,  318,  306,  308,  310,
      312,  320, 1212, 1280,  317,  322,  326,  327,  336, 1211,
     1280,  338,  341,  343,  328,  329,  349,  354,  355,  344,
      346,  237,  352,  357,  361,  362,  364,  367,  358,  363,
      378, 1210, 1280, 1209, 1280, 1208, 1280, 1280,  375,  376,

      371,  390,  393,  389,  392,  386,  403,  428,  384,  410,
      418,  409,  416, 1207, 1280,  411,  414,  421,  424,  439,
      415,  423,  437,  400,  434,  435,  448,  449, 1206, 1280,
      447,  451,  452,  457,  461,  466,  476,  468,  465,  481,
      478, 1280,  485,  492,  472,  495,  499,  504,  516,  512,
     1280,  511,  523,  527,  529,  531,  509,  552,  579, 1237,
     1234,  524,  525,  510,  532, 1194, 1280,  522,  537,  543,
      544,  547,  550,  554,  556, 1193, 1280, 1192, 1280,  575,
      577,  576,  580,  591, 1187, 1280,  584,  600,  592,  595,
      603,  601,  602,  614,  615,  620,  612,  618,  623,  624,

      621,  616,  626,  629,  630,  627,  631,  654,  640,  643,
      659,  645,  646,  639,  660,  668, 1184, 1280, 1183, 1280,
     1280, 1177, 1280,  653,  662,  663, 1162, 1280,  665,  673,
      674, 1132, 1280,  677,  671,  679,  693,  688,  687,  678,
      685,  691,  698,  718,  702,  715,  717, 1280,  725,  709,
      712,  732,  730, 1280,  731,  727,  739,  735,  755,  736,
      744,  749,  745,  782, 1047, 1280, 1026, 1280,  984, 1280,
      978, 1280, 1280,  750,  754,  753,  757,  766,  770,  781,
      765,  775,  779,  780,  797,  922, 1280,  787,  794,  795,
      791,  809,  796,  798,  812,  815,  819,  825,  824,  826,

      827,  831,  837,  830,  841,  846,  859,  839,  843,  818,
      842,  861,  848, 1280,  801, 1280,  863,  868,  849,  856,
      864,  881,  889,  886,  870,  874,  885,  883,  882,  902,
      899, 1280,  901,  912,  900,  918, 1280,  931,  925,  958,
      762, 1280,  916,  919,  909,  923,  929,  936,  942,  941,
      947,  952,  928,  943,  746, 1280,  955,  960,  961,  963,
      959,  965,  970,  972,  974,  983,  993,  711,  987,  992,
     1280,  996,  988,  997,  999, 1017,  682, 1280,  611, 1280,
     1280,  980, 1013, 1019, 1280, 1004, 1014,  953, 1027, 1029,
     1033, 1043, 1038, 1048, 1024, 1035, 1075,  610, 1280,  558,

     1036, 1045, 1050, 1054, 1042, 1064, 1070,  488, 1280,  477,
     1280, 1065, 1069,  445, 1280, 1066, 1073, 1082, 1084, 1098,
     1080, 1099, 1100, 1105, 1101, 1104, 1108, 1280, 1280, 1119,
     1111, 1102, 1134,  381, 1280, 1093, 1115, 1103, 1118, 1135,
     1136, 1138, 1140, 1143, 1145, 1148, 1149, 1151, 1152, 1154,
     1155, 1164, 1169, 1150, 1180, 1163, 1165,  351, 1280, 1170,
      230, 1280,  184, 1280, 1280,  164, 1280, 1280, 1280, 1179,
     1185, 1280, 1186, 1174, 1175, 1189, 1191, 1188, 1190, 1181,
     1195,   65, 1280, 1280, 1239,   67, 1241, 1243, 1245
    } ;

static const flex_int16_t yy_def[590] =
    {   0,
      584,    1,  585,  585,  585,  585,  585,  585,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  587,  584,
      588,  584,  589,  584,  584,  586,  586,  586,  584,  586,
      584,  586,  586,  586,  584,  586,  586,  584,  586,  586,
      584,  586,  586,  586,  584,  586,  584,  586,  586,  586,
      584,  586,  586,  584,  586,  584,  586,  586,  584,  586,

      586,  584,  586,  586,  586,  584,  586,  584,  586,  584,
      586,  586,  586,  584,  586,  586,  584,  586,  584,  586,
      586,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      587,  584,  588,  584,  589,  584,  584,  584,  586,  584,
      586,  584,  584,  586,  584,  586,  584,  586,  584,  586,
      584,  584,  586,  584,  586,  584,  584,  586,  584,  586,
      584,  584,  586,  584,  586,  584,  586,  584,  584,  586,
      584,  586,  584,  586,  584,  584,  586,  584,  586,  584,
      584,  586,  584,  586,  584,  586,  584,  584,  586,  584,

      586,  586,  584,  586,  584,  584,  584,  584,  586,  586,
      584,  584,  584,  586,  584,  586,  584,  586,  584,  584,
      586,  586,  584,  586,  584,  584,  584,  584,  586,  584,
      586,  584,  586,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  586,  584,  586,  584,  586,  584,  586,  584,  586,
      584,  584,  584,  586,  584,  586,  584,  586,  584,  586,
      584,  586,  584,  584,  586,  584,  586,  584,  586,  584,
      584,  586,  584,  586,  584,  584,  586,  584,  586,  584,

      586,  586,  586,  584,  584,  584,  584,  584,  586,  584,
      584,  586,  584,  586,  584,  584,  586,  584,  586,  584,
      584,  586,  584,  586,  584,  584,  586,  584,  584,  586,
      584,  586,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  586,  584,  586,  584,  586,  584,
      586,  584,  584,  586,  584,  586,  584,  586,  584,  584,
      586,  584,  586,  584,  584,  586,  584,  586,  584,  584,
      586,  584,  586,  584,  586,  584,  586,  584,  586,  584,

      584,  584,  584,  586,  584,  584,  584,  586,  584,  586,
      584,  584,  586,  584,  586,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      586,  584,  586,  584,  586,  584,  584,  586,  584,  586,
      584,  584,  586,  584,  586,  584,  586,  584,  586,  584,
      586,  584,  586,  584,  584,  584,  584,  586,  586,  584,
      584,  584,  584,  584,  584,  584,  586,  584,  586,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  586,  584,  586,

      584,  584,  586,  584,  586,  584,  584,  586,  584,  586,
      584,  586,  584,  586,  584,  586,  584,  584,  584,  584,
      586,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  586,  584,  586,  584,  586,  584,  584,
      586,  584,  586,  584,  584,  586,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  586,  584,  586,  584,  584,
      586,  584,  586,  584,  584,  586,  584,  584,  584,  584,
      584,  584,  584,  586,  584,  586,  584,  586,  584,  586,
      584,  586,  584,    0,  584,  584,  584,  584,  584
    } ;

static const flex_int16_t yy_nxt[1326] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   34,   34,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   34,
       47,   48,   49,   50,   10,   52,   52,   54,   54,   56,
       53,   53,   55,   55,   56,   62,   64,   70,   65,   67,
       63,   86,   68,   72,   76,   79,   95,   80,   66,  147,
       77,  148,   69,   87,   73,   82,   88,   74,   96,   71,
       81,   83,   78,   89,   90,  107,   84,   92,   97,   75,
      100,   57,  151,   85,   98,   93,   57,   91,  103,  109,

      118,  101,  152,  111,  120,  121,   99,  108,  584,  154,
      112,  102,  115,   94,  104,  138,  116,  105,  113,  149,
      139,  110,  114,  122,  106,  117,  119,  123,   64,  155,
       65,  124,  125,  158,  126,  127,  155,  150,  128,  129,
      130,  131,  150,  132,  133,  156,  134,  170,  160,  135,
      152,  159,  163,  136,  157,  171,  155,  165,  164,  159,
      153,  161,  166,  168,  161,  164,  166,  173,  157,  169,
      171,  167,  169,  175,  177,  182,  187,  162,  172,  174,
      180,  178,  174,  176,  176,  181,  183,  178,  181,  184,
      189,  191,  183,  181,  179,  185,  192,  185,  193,  194,

      196,  188,  195,  186,  199,  201,  204,  584,  197,  197,
      214,  202,  216,  218,  195,  190,  191,  198,  215,  193,
      209,  193,  212,  203,  219,  205,  200,  584,  200,  215,
      217,  205,  206,  210,  217,  213,  224,  215,  207,  221,
      233,  219,  231,  229,  211,  230,  211,  225,  234,  222,
      208,  226,  220,  230,  232,  230,  205,  223,  225,  159,
      232,  227,  188,  200,  234,  287,  212,  217,  178,  228,
      155,  232,  235,  584,  190,  183,  169,  230,  157,  213,
      288,  248,  215,  242,  239,  241,  183,  236,  226,  238,
      237,  234,  193,  164,  225,  206,  262,  219,  243,  240,

      263,  207,  161,  152,  138,  176,  244,  245,  219,  139,
      166,  264,  260,  247,  261,  246,  225,  159,  249,  250,
      251,  252,  263,  155,  263,  253,  263,  265,  239,  265,
      254,  207,  255,  256,  257,  258,  266,  164,  166,  267,
      268,  267,  269,  259,  270,  265,  271,  274,  276,  269,
      263,  269,  275,  271,  272,  271,  275,  277,  267,  277,
      275,  267,  278,  273,  279,  275,  280,  281,  282,  275,
      277,  281,  281,  283,  283,  285,  279,  286,  289,  277,
      288,  277,  290,  290,  279,  292,  279,  286,  293,  286,
      288,  294,  283,  281,  584,  288,  295,  283,  284,  293,

      290,  295,  297,  298,  290,  291,  295,  293,  299,  301,
      293,  295,  305,  302,  300,  312,  306,  309,  298,  298,
      310,  296,  305,  300,  584,  303,  306,  313,  307,  300,
      300,  314,  310,  304,  327,  310,  308,  315,  307,  315,
      313,  317,  319,  328,  318,  320,  304,  305,  324,  313,
      322,  306,  313,  315,  318,  298,  310,  318,  323,  315,
      320,  316,  325,  307,  320,  300,  325,  320,  328,  318,
      323,  311,  323,  325,  325,  330,  332,  328,  323,  331,
      326,  333,  321,  328,  323,  333,  279,  335,  584,  331,
      331,  325,  329,  298,  331,  333,  331,  315,  318,  277,

      333,  265,  279,  286,  334,  333,  290,  313,  279,  336,
      325,  338,  269,  290,  295,  286,  263,  325,  305,  337,
      584,  340,  306,  283,  339,  275,  286,  323,  341,  271,
      354,  584,  310,  281,  307,  342,  300,  293,  343,  298,
      367,  318,  344,  313,  310,  328,  283,  345,  263,  295,
      351,  331,  354,  368,  348,  347,  369,  288,  323,  346,
      300,  271,  368,  365,  366,  370,  349,  366,  366,  281,
      350,  370,  352,  290,  353,  368,  333,  325,  371,  372,
      370,  370,  372,  286,  370,  372,  372,  372,  534,  374,
      373,  375,  376,  373,  377,  355,  263,  375,  356,  375,

      357,  535,  306,  333,  358,  381,  298,  359,  377,  360,
      361,  378,  295,  362,  363,  379,  300,  281,  377,  379,
      377,  382,  364,  379,  382,  383,  379,  382,  384,  386,
      387,  388,  389,  391,  380,  384,  384,  389,  384,  392,
      393,  394,  395,  382,  387,  387,  385,  399,  387,  397,
      401,  396,  400,  584,  584,  392,  410,  389,  389,  398,
      398,  392,  398,  390,  396,  404,  394,  394,  405,  400,
      398,  394,  402,  396,  400,  401,  394,  411,  408,  409,
      406,  413,  411,  405,  405,  411,  405,  398,  409,  409,
      414,  414,  398,  414,  415,  416,  414,  403,  416,  387,

      392,  409,  407,  411,  389,  414,  414,  387,  414,  416,
      411,  412,  370,  414,  387,  377,  416,  416,  384,  414,
      416,  370,  417,  368,  384,  584,  409,  405,  419,  411,
      389,  416,  389,  420,  419,  394,  418,  379,  392,  401,
      405,  421,  394,  387,  427,  423,  416,  377,  396,  411,
      409,  398,  427,  382,  584,  411,  411,  366,  424,  414,
      425,  422,  379,  414,  384,  368,  400,  387,  426,  366,
      430,  375,  384,  429,  419,  428,  433,  409,  432,  375,
      405,  441,  431,  370,  372,  442,  443,  409,  400,  584,
      444,  445,  373,  442,  448,  446,  444,  442,  434,  435,

      444,  450,  451,  436,  449,  584,  446,  405,  449,  446,
      437,  455,  368,  446,  444,  438,  370,  439,  449,  451,
      453,  366,  451,  451,  447,  440,  449,  454,  454,  456,
      454,  457,  459,  458,  456,  460,  461,  454,  454,  458,
      452,  458,  462,  463,  584,  464,  464,  460,  462,  468,
      464,  460,  456,  479,  462,  460,  464,  460,  460,  477,
      471,  480,  462,  478,  469,  464,  473,  464,  462,  464,
      465,  451,  458,  470,  466,  472,  462,  480,  475,  473,
      467,  478,  478,  456,  470,  480,  478,  442,  478,  474,
      485,  584,  451,  472,  458,  442,  480,  444,  462,  442,

      464,  460,  476,  480,  481,  471,  456,  482,  471,  458,
      446,  481,  449,  485,  446,  444,  458,  458,  480,  454,
      472,  451,  460,  472,  467,  444,  486,  446,  446,  484,
      449,  471,  483,  490,  480,  491,  498,  464,  473,  499,
      500,  449,  488,  492,  449,  487,  472,  449,  462,  499,
      446,  478,  501,  451,  501,  489,  442,  503,  505,  499,
      501,  493,  499,  504,  506,  584,  501,  508,  495,  506,
      506,  509,  502,  504,  494,  462,  510,  475,  496,  504,
      451,  511,  509,  446,  506,  504,  509,  449,  514,  442,
      506,  490,  472,  491,  515,  507,  506,  512,  511,  513,

      499,  497,  515,  511,  513,  516,  513,  517,  515,  517,
      513,  521,  515,  517,  511,  517,  522,  518,  517,  513,
      522,  584,  515,  499,  513,  504,  519,  584,  517,  513,
      522,  513,  517,  513,  517,  522,  520,  522,  511,  522,
      518,  522,  517,  522,  501,  501,  515,  504,  504,  499,
      513,  522,  517,  513,  511,  501,  524,  526,  509,  504,
      523,  538,  525,  499,  511,  506,  535,  501,  509,  584,
      527,  513,  528,  517,  513,  535,  511,  515,  513,  535,
      536,  530,  509,  539,  537,  539,  529,  543,  535,  539,
      584,  531,  506,  537,  544,  499,  532,  537,  541,  522,

      537,  546,  542,  544,  515,  544,  501,  539,  542,  544,
      517,  513,  542,  540,  509,  542,  544,  542,  533,  544,
      547,  548,  547,  547,  558,  545,  547,  545,  556,  547,
      539,  542,  537,  542,  535,  535,  557,  542,  537,  559,
      544,  545,  547,  549,  547,  537,  559,  551,  550,  537,
      557,  552,  542,  539,  539,  548,  559,  561,  557,  562,
      563,  559,  553,  564,  554,  564,  562,  542,  566,  567,
      557,  568,  568,  562,  567,  584,  562,  555,  560,  562,
      574,  562,  575,  564,  567,  557,  564,  575,  565,  564,
      562,  567,  567,  557,  568,  569,  575,  567,  562,  557,

      568,  572,  575,  575,  557,  584,  575,  570,  575,  576,
      577,  582,  571,  575,  578,  557,  579,  577,  577,  580,
      584,  581,  575,  573,  583,  583,  584,  584,  575,  575,
      584,  581,  579,  581,  579,  584,  584,  584,  583,   51,
       51,  141,  141,  143,  143,  145,  145,  261,  147,  584,
      584,  584,  584,  584,  584,  584,  584,  148,  146,  144,
      142,  137,  584,  584,  584,  584,  584,  146,  144,  142,
       58,  140,  137,  584,   61,   60,   59,   58,  584,    9,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,

      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584
    } ;

static const flex_int16_t yy_chk[1326] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    5,    6,    7,
        3,    4,    5,    6,    8,   22,   23,   28,   23,   27,
       22,   33,   27,   29,   30,   31,   37,   31,  586,   64,
       30,   64,   27,   33,   29,   32,   35,   29,   37,   28,
       31,   32,   30,   35,   35,   41,   32,   36,   38,   29,
       39,    7,   68,   32,   38,   36,    8,   35,   40,   42,

       45,   39,   68,   43,   46,   46,   38,   41,  582,   70,
       43,   39,   44,   36,   40,   53,   44,   40,   43,   67,
       53,   42,   43,   46,   40,   44,   45,   50,   65,   70,
       65,   50,   50,   73,   50,   50,   71,   69,   50,   50,
       50,   50,   67,   50,   50,   72,   50,   80,   74,   50,
       69,   75,   76,   50,   72,   81,   71,   77,   76,   73,
       69,   74,   77,   79,   75,   78,   78,   82,   75,   81,
       80,   78,   79,   83,   84,   89,   92,   75,   81,   85,
       86,   85,   82,   83,   85,   87,   89,   84,   86,   90,
       93,   94,   91,   87,   85,   91,   95,   90,   96,   97,

       98,   92,   99,   91,  103,  104,  105,  566,   98,   99,
      109,  104,  111,  113,   97,   93,   94,   99,  109,   95,
      107,   96,  108,  104,  113,  106,  106,  563,  103,  110,
      114,  105,  106,  107,  111,  108,  116,  110,  106,  115,
      121,  114,  120,  118,  107,  119,  108,  117,  121,  115,
      106,  117,  114,  118,  122,  119,  134,  115,  116,  128,
      120,  117,  123,  123,  122,  182,  124,  126,  134,  117,
      124,  126,  122,  561,  127,  129,  128,  123,  123,  124,
      182,  134,  124,  130,  127,  128,  129,  123,  130,  126,
      124,  127,  131,  127,  133,  132,  151,  135,  130,  127,

      152,  132,  131,  132,  138,  131,  130,  131,  135,  138,
      131,  154,  147,  132,  147,  131,  133,  136,  136,  136,
      136,  136,  151,  136,  153,  136,  152,  155,  136,  154,
      136,  136,  136,  136,  136,  136,  156,  136,  136,  157,
      158,  162,  159,  136,  160,  155,  161,  165,  168,  158,
      153,  159,  166,  160,  162,  161,  167,  169,  156,  172,
      165,  157,  173,  162,  174,  166,  175,  176,  177,  167,
      168,  175,  176,  178,  179,  180,  179,  181,  184,  169,
      183,  172,  185,  186,  173,  187,  174,  180,  188,  181,
      186,  189,  177,  179,  558,  183,  190,  178,  179,  191,

      184,  189,  199,  200,  185,  186,  190,  187,  201,  202,
      188,  191,  203,  202,  201,  209,  203,  204,  199,  200,
      205,  191,  207,  206,  534,  202,  207,  209,  203,  206,
      203,  210,  204,  202,  224,  205,  203,  213,  207,  211,
      212,  216,  218,  224,  217,  219,  207,  208,  222,  211,
      221,  208,  212,  210,  216,  208,  208,  217,  221,  213,
      220,  211,  223,  208,  218,  208,  222,  219,  225,  220,
      226,  208,  223,  227,  228,  231,  233,  225,  226,  232,
      223,  234,  220,  228,  228,  235,  239,  236,  514,  235,
      231,  227,  228,  236,  232,  233,  238,  237,  238,  241,

      234,  237,  240,  245,  235,  240,  243,  237,  239,  236,
      243,  238,  241,  244,  240,  245,  247,  244,  247,  237,
      510,  241,  247,  248,  240,  246,  246,  244,  243,  246,
      257,  508,  248,  246,  247,  244,  247,  249,  246,  250,
      264,  252,  247,  250,  249,  252,  254,  248,  256,  249,
      255,  253,  257,  264,  252,  250,  268,  255,  253,  249,
      253,  254,  265,  262,  263,  268,  253,  262,  263,  256,
      254,  269,  255,  258,  256,  265,  258,  258,  270,  271,
      269,  272,  272,  258,  273,  273,  270,  271,  500,  274,
      272,  275,  280,  273,  281,  258,  259,  274,  259,  275,

      259,  500,  259,  259,  259,  287,  259,  259,  284,  259,
      259,  282,  259,  259,  259,  283,  259,  259,  280,  282,
      281,  288,  259,  283,  291,  289,  284,  287,  290,  292,
      293,  294,  295,  297,  284,  289,  291,  296,  290,  298,
      299,  300,  301,  288,  292,  293,  291,  303,  296,  302,
      304,  305,  307,  498,  479,  297,  314,  294,  295,  302,
      306,  298,  304,  296,  301,  309,  299,  300,  310,  303,
      306,  308,  304,  305,  307,  308,  311,  315,  312,  313,
      311,  324,  314,  309,  311,  316,  310,  308,  312,  313,
      325,  326,  311,  329,  330,  331,  324,  308,  334,  335,

      336,  316,  311,  315,  339,  325,  326,  336,  329,  338,
      337,  316,  340,  341,  335,  343,  330,  331,  341,  342,
      334,  340,  336,  337,  342,  477,  337,  345,  341,  351,
      339,  338,  346,  343,  342,  344,  337,  345,  347,  344,
      346,  343,  349,  346,  350,  345,  349,  353,  356,  352,
      347,  344,  350,  352,  468,  351,  357,  344,  346,  355,
      347,  344,  356,  358,  355,  358,  363,  357,  349,  353,
      356,  360,  357,  353,  355,  352,  359,  361,  358,  360,
      359,  374,  357,  362,  362,  375,  376,  361,  363,  455,
      377,  378,  362,  374,  381,  379,  376,  375,  359,  364,

      377,  383,  384,  364,  382,  441,  380,  364,  381,  378,
      364,  391,  364,  379,  380,  364,  364,  364,  382,  385,
      388,  364,  383,  384,  380,  364,  385,  389,  390,  392,
      388,  393,  395,  394,  391,  396,  397,  389,  390,  393,
      385,  394,  398,  399,  415,  400,  401,  401,  402,  404,
      402,  402,  392,  410,  403,  395,  403,  403,  396,  408,
      405,  410,  397,  409,  404,  406,  406,  399,  398,  400,
      401,  419,  403,  404,  402,  405,  407,  411,  407,  407,
      403,  412,  408,  417,  405,  411,  409,  420,  418,  406,
      425,  413,  419,  407,  407,  421,  412,  421,  422,  420,

      422,  422,  407,  418,  412,  424,  417,  421,  423,  426,
      427,  418,  428,  425,  423,  429,  422,  426,  428,  424,
      424,  431,  430,  423,  422,  429,  428,  430,  427,  424,
      433,  434,  423,  435,  431,  435,  443,  436,  436,  444,
      445,  434,  431,  435,  433,  430,  434,  436,  438,  447,
      439,  438,  445,  438,  446,  434,  439,  448,  450,  443,
      447,  436,  444,  449,  451,  386,  446,  453,  439,  452,
      488,  453,  447,  452,  438,  440,  457,  440,  440,  448,
      440,  458,  454,  440,  450,  449,  454,  440,  461,  440,
      451,  440,  440,  440,  462,  452,  488,  459,  457,  460,

      482,  440,  461,  458,  459,  463,  460,  464,  462,  465,
      465,  469,  466,  463,  467,  464,  470,  465,  466,  466,
      472,  371,  467,  482,  473,  486,  466,  369,  467,  467,
      469,  473,  474,  474,  475,  470,  467,  483,  476,  472,
      474,  476,  475,  484,  483,  487,  476,  486,  489,  490,
      487,  489,  476,  476,  491,  495,  483,  487,  484,  493,
      476,  505,  484,  492,  492,  494,  501,  495,  490,  367,
      489,  496,  490,  493,  493,  502,  491,  494,  496,  501,
      503,  493,  492,  506,  504,  505,  492,  516,  502,  507,
      365,  494,  497,  503,  517,  497,  497,  504,  512,  497,

      507,  521,  513,  518,  497,  519,  497,  506,  512,  516,
      497,  497,  513,  507,  497,  518,  517,  519,  497,  520,
      522,  523,  525,  521,  538,  518,  524,  519,  536,  527,
      531,  520,  532,  523,  526,  524,  536,  526,  527,  539,
      530,  520,  522,  523,  525,  532,  538,  526,  524,  530,
      537,  527,  530,  533,  531,  533,  540,  541,  537,  542,
      543,  539,  530,  544,  533,  545,  545,  533,  546,  547,
      540,  548,  549,  549,  550,  332,  551,  533,  540,  541,
      556,  542,  557,  543,  552,  554,  544,  560,  545,  553,
      553,  546,  547,  554,  548,  549,  570,  550,  551,  552,

      555,  555,  571,  573,  553,  327,  556,  552,  557,  574,
      575,  580,  553,  560,  576,  555,  577,  574,  575,  578,
      322,  579,  570,  555,  580,  581,  319,  317,  571,  573,
      285,  578,  576,  579,  577,  278,  276,  266,  581,  585,
      585,  587,  587,  588,  588,  589,  589,  261,  260,  229,
      214,  196,  194,  192,  170,  163,  149,  148,  145,  143,
      141,  137,  112,  101,  100,   88,   66,   63,   61,   59,
       58,   55,   52,   34,   17,   15,   14,   11,    9,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,

      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584,  584,  584,  584,  584,  584,
      584,  584,  584,  584,  584
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "PascalDSL.l"
#line 2 "PascalDSL.l"
# include "common.h"
# include "PascalDSL.tab.h"

char buffer[200];
typedef void (*addParserErrorText)(char* message);
static addParserErrorText m_addParserErrorText;

int count(void);
void* addTextPtr;

int yy_pascal_count(void) { return yylineno; }
int yy_pascal_lex_get_line(void) { return yy_pascal_count(); }
int yy_pascal_lex_getlines(void) { return yy_pascal_count(); }
#line 1196 "lex.pascal.c"

#line 1198 "lex.pascal.c"

#define INITIAL 0
#define Comment1 1
#define Comment2 2
#define Comment3 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 48 "PascalDSL.l"


#line 1421 "lex.pascal.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 585 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1280 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 50 "PascalDSL.l"
{ yy_pascal_count(); /* DO NOTHING */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 51 "PascalDSL.l"
{ yy_pascal_count(); /* DO NOTHING */ ++yylineno; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "PascalDSL.l"
{ yy_pascal_count(); /* DO NOTHING */ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 54 "PascalDSL.l"
{ yy_pascal_count(); /* DO NOTHING */ ++yylineno; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "PascalDSL.l"
{ yy_pascal_count(); /* DO NOTHING */ }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 57 "PascalDSL.l"
{ yy_pascal_count(); /* DO NOTHING */ ++yylineno; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 59 "PascalDSL.l"
{ yy_pascal_count(); BEGIN(Comment1); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 60 "PascalDSL.l"
{ yy_pascal_count(); ++yylineno;      }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "PascalDSL.l"
{ yy_pascal_count(); BEGIN(INITIAL);  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "PascalDSL.l"
{ yy_pascal_count(); BEGIN(Comment2); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 64 "PascalDSL.l"
{ yy_pascal_count(); ++yylineno;      }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "PascalDSL.l"
{ yy_pascal_count(); BEGIN(INITIAL);  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 "PascalDSL.l"
{ yy_pascal_count(); BEGIN(Comment3); }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 68 "PascalDSL.l"
{ yy_pascal_count(); ++yylineno;      }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 69 "PascalDSL.l"
{ yy_pascal_count(); BEGIN(INITIAL);  }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 71 "PascalDSL.l"
{ /* empty */ }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 72 "PascalDSL.l"
{ yy_pascal_count(); ++yylineno; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 74 "PascalDSL.l"
{ return TOK_PAS_RANGE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 76 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_AND; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 77 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_ARRAY; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 78 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_BEGIN; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 79 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_CASE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 80 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_CLASS; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 81 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_CONST; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 82 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_DIV; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 83 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_DO; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 84 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_DOWNTO; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 85 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_ELSE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 86 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_END; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 87 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_FILE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 88 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_FOR; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 89 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_FORWARD; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 90 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_FUNCTION; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 91 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_GOTO; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 92 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_IF; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 93 "PascalDSL.l"
{
                                yy_pascal_count(); return TOK_PAS_IMPLEMENTATION; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 95 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_IN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 96 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_INTERFACE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 97 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_LABEL; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 98 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_LIBRARY; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 99 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_MOD; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 100 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_NIL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 101 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_NOT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 102 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_OF; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 103 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_OR; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 104 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_PACKED; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 105 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_PRIVATE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 106 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_PROCEDURE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 107 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_PROGRAM; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 108 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_PROTECTED; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 109 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_PUBLIC; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 110 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_PUBLISHED; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 111 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_RECORD; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 112 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_REPEAT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 113 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_SET; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 114 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_THEN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 115 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_TO; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 116 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_TYPE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 117 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_UNIT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 118 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_UNTIL; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 119 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_USES; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 120 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_VAR; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 121 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_WHILE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 122 "PascalDSL.l"
{ yy_pascal_count(); return TOK_PAS_WITH; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 124 "PascalDSL.l"
{ return TOK_PAS_ID;  }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 126 "PascalDSL.l"
{ return TOK_PAS_NUMBER; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 127 "PascalDSL.l"
{ return TOK_PAS_FLOAT;  }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 129 "PascalDSL.l"
{ return ';'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 130 "PascalDSL.l"
{ return ':'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 131 "PascalDSL.l"
{ return '.'; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 132 "PascalDSL.l"
{ return ','; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 133 "PascalDSL.l"
{ return '='; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 134 "PascalDSL.l"
{ return '('; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 135 "PascalDSL.l"
{ return ')'; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 136 "PascalDSL.l"
{ return '['; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 137 "PascalDSL.l"
{ return ']'; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 139 "PascalDSL.l"
{ return '+'; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 140 "PascalDSL.l"
{ return '-'; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 141 "PascalDSL.l"
{ return '*'; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 142 "PascalDSL.l"
{ return '/'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 144 "PascalDSL.l"
{
  sprintf( buffer, "Unrecognized character: %s\n", yytext );
  pascalerror(buffer);
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 149 "PascalDSL.l"
ECHO;
	YY_BREAK
#line 1899 "lex.pascal.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(Comment1):
case YY_STATE_EOF(Comment2):
case YY_STATE_EOF(Comment3):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 585 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 585 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 584);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 149 "PascalDSL.l"


void yy_pascal_lex_parser_error(void (*func)(char*)) {
  m_addParserErrorText = func;
}

int pascalwrap(void) { return 1; }

void pascalerror(char* m)
{
  char bu[320];
  sprintf(bu,"error: %d: %s",
  yylineno, m);
  m_addParserErrorText(bu);
}

BOOL yy_pascal_lex_main(char* filename)
{
  BOOL result;
  yyin = fopen(filename,"r");
  if (!yyin) {
    sprintf(buffer, "could not open file: %s", filename);
    m_addParserErrorText(buffer);
    return false;
  }

  //yylex();
  result = pascalparse();
  fclose(yyin);

  return result;
}

void yy_pascal_lex_close(void) {
  fclose(yyin);
}

void __declspec(dllexport) yy_pascal_lex_parser_error(void (*func)(char*));
void __declspec(dllexport) yy_pascal_lex_close(void);

int  __declspec(dllexport) yy_pascal_lex_get_line(void);
int  __declspec(dllexport) yy_pascal_lex_getlines(void);

BOOL __declspec(dllexport) yy_pascal_lex_main(char* filename);

